version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsdom
    versions:
    - 16.5.2
  - dependency-name: serialize-javascript
    versions:
    - 4.0.0
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: sshpk
    versions:
    - 1.16.1
  - dependency-name: mixin-deep
    versions:
    - 1.3.2
  - dependency-name: extend
    versions:
    - 3.0.2
  - dependency-name: mem
    versions:
    - 4.3.0
  - dependency-name: url-parse
    versions:
    - 1.5.1
  - dependency-name: querystringify
    versions:
    - 2.2.0
  - dependency-name: set-value
    versions:
    - 2.0.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: tough-cookie
    versions:
    - 2.5.0
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: randomatic
    versions:
    - 3.1.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: node-forge
    versions:
    - 0.10.0
  - dependency-name: debug
    versions:
    - 2.6.9
  - dependency-name: babel-loader
    versions:
    - 7.1.5
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: chai
    versions:
    - 4.3.4
